{% set version = "0.0.2" %}

package:
  name: mypyc-ipython
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/m/mypyc-ipython/mypyc_ipython-{{ version }}.tar.gz
    sha256: e265704ac98c3c42df404d7066f8c122a6fcb4ef6d88410ed84d60979d1b6bea
  # TODO: remove after https://github.com/c-bata/mypyc_ipython/pull/1
  - url: https://raw.githubusercontent.com/c-bata/mypyc_ipython/v{{ version }}/LICENSE
    sha256: e09fe0518793ad90e295d386047f1afedecf600d96953b4402d967bc285e4ea7

build:
  number: 3
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - c-compiler
    - ipython
    - mypy >=0.800
    - python >={{ python_min }}

test:
  files:
    - test_mypyc_ipython.py
  requires:
    - ipython
    - pip
    - coverage
    - python {{ python_min }}
  imports:
    - mypyc_ipython
  commands:
    - pip check
    - coverage run --branch --source mypyc_ipython -m IPython test_mypyc_ipython.py
    - coverage report --show-missing --skip-covered --fail-under 88

about:
  home: https://github.com/c-bata/mypyc_ipython
  summary: IPython magic command interface for interactive work with mypyc.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
